import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, {useRef,  useState, useEffect } from 'react';
import { Fade } from "react-awesome-reveal";
import Header from './components/header.js'
import { Navigation, Pagination, Scrollbar, A11y } from 'swiper';
import { Swiper, SwiperSlide } from 'swiper/react';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';
import ReactTooltip from 'react-tooltip';
import "swiper/css/effect-cards"
import SwiperCore, {
    EffectCards
  } from 'swiper';
  SwiperCore.use([EffectCards]);

export default function Home() {
  const [menu, setMenu] = useState(true)
  const [blur, setBlur] = useState(false)
  const [tab, setTab] = useState(0)
  const [rightOpen, setRightOpen] = useState(false)
  const [wallet, setWallet] = useState('')
  const n = 15;


  const toggleSidebar = (event) => {
    setRightOpen(!rightOpen)
  }

  const disconnect = () => {
    window.solana.disconnect();
    setWallet('');
  }




  return (
    <div >
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Favicon.png" />
      </Head>


      {tab==0 ?
            <Fade>
        <div className={styles.home_container}>
          <div className={styles.top_bar}>
            <div hidden className={styles.mint_total}>
              <h1>5000<span>AVAILABLE</span></h1>
            </div>
            <Fade delay={1000} className={styles.logoimg}>
              <img  src='/222 (1).svg'/>
            </Fade>
            {wallet=='' ? 
            <button onClick={toggleSidebar}>CONNECT WALLET</button>
            :<img className={styles.wallet_connected} src='/assets/Wallet Connected.svg'/>}
          </div>
          <Fade delay={600} className={styles.comingsoon}>
              <h1>COMING SOON</h1>
            </Fade>
        </div>
            </Fade>
      :''}

      {tab==1 ?
        <Fade>
          <div className={styles.about_container}>
            <div className={styles.top_bar}>
              <div hidden className={styles.mint_total}>
                <h1>5000<span>AVAILABLE</span></h1>
              </div>
              <h1 className={styles.nav_title}>ABOUT</h1>
              {wallet=='' ? 
              <button onClick={toggleSidebar}>CONNECT WALLET</button>
              :<img className={styles.wallet_connected} src='/assets/Wallet Connected.svg'/>}
            </div>
            <div className={styles.about_wrapper}>
              <h1>What is MoonwalkerFM </h1>
              <p>Lo-Fi Moonwalkers is the first NFT collection from MoonwalkerFM connecting Artists & Investors in a way never seen before. For the first time fans can be a part of the success of a song that they love in real time. But what are Moonwalkers? By nature they were an angry & unpleasant species. fur-covered aliens from a distant galaxy. Always discontent & unsatisfied with their way of living… one day, a Millenia ago, an ancient tape was discovered. this tape contained a series of audio files which brought peace & serenity to the Moonwalkers. they called this music. Lo-Fi. This inspired them to work together to explore the universe to discover new music, to keep their world safe & to never return to the days of old...</p>
              <div className={styles.horizontal_line}></div>
              <div className={styles.bottom_about}>
                <img src='/demo5.jpg'/>
                <div className={styles.about_price}>
                  <h3>MW PRICE: 0.06Ξ</h3>
                  <p>Every NFT minted gets paired with a full-length Lo-Fi song from streaming platforms, as the seasons roll out.
The NFT holders of these songs can take home up to 45% streaming royalties.</p>
                </div>
              </div>
              <img className={styles.utilitypng} src='utility.png'/>
            </div>
          </div>
        </Fade>
      :''}

      {tab==2 ?
        <Fade>
          <div className={styles.traits_container}>
            <div className={styles.top_bar}>
              <div hidden className={styles.mint_total}>
                <h1>5000<span>AVAILABLE</span></h1>
              </div>
              <h1 className={styles.nav_title}>TRAITS</h1>
              {wallet=='' ? 
              <button onClick={toggleSidebar}>CONNECT WALLET</button>
              :<img className={styles.wallet_connected} src='/assets/Wallet Connected.svg'/>}
            </div>
            <Swiper className={styles.swiper} effect={'cards'} grabCursor={true} >
              <SwiperSlide className={styles.swiper_slide}>Slide 1</SwiperSlide>
              <SwiperSlide className={styles.swiper_slide}>Slide 2</SwiperSlide>
              <SwiperSlide className={styles.swiper_slide}>Slide 3</SwiperSlide>
              <SwiperSlide className={styles.swiper_slide}>Slide 4</SwiperSlide>
              <SwiperSlide className={styles.swiper_slide}>Slide 5</SwiperSlide>
              <SwiperSlide className={styles.swiper_slide}>Slide 6</SwiperSlide>
              <SwiperSlide className={styles.swiper_slide}>Slide 7</SwiperSlide>
              <SwiperSlide className={styles.swiper_slide}>Slide 8</SwiperSlide>
              <SwiperSlide className={styles.swiper_slide}>Slide 9</SwiperSlide>
            </Swiper>
          </div>
        </Fade>
      :''}

      {tab==3 ?
        <Fade>
          <div className={styles.roadmap_container}>
            <div className={styles.top_bar}>
              <div hidden className={styles.mint_total}>
                <h1 >5000<span>AVAILABLE</span></h1>
              </div>
              <h1 className={styles.nav_title}>ROADMAP</h1>
              {wallet=='' ? 
              <button onClick={toggleSidebar}>CONNECT WALLET</button>
              :<img className={styles.wallet_connected} src='/assets/Wallet Connected.svg'/>}
            </div>
          <img data-tip data-for='sadFace' className={styles.planety} src='planeuta__x2B__Layer_7_xA0_Image.png'/>
          <ReactTooltip id='sadFace' type='dark' effect='solid'>
            <span>0% minted</span>
            <p>- Mint 100 NFTs for team, giveaways & prize pools!</p>
          </ReactTooltip>
          <img data-tip data-for='2' className={styles.planety} src='planeuta__x2B__Layer_7_xA0_Image (1).png'/>
          <ReactTooltip id='2' type='dark' effect='solid'>
            <span>20% minted</span>
            <p>- Pay team & contributors<br/>
              - Moonwalker Ethereum Competition<br/>
              - Season Zero Preview<br/></p>
          </ReactTooltip>
          <img data-tip data-for='3' className={styles.planety} src='planeuta__x2B__Layer_7_xA0_Image (2).png'/>
          <ReactTooltip id='3' type='dark' effect='solid'>
            <span>40% minted</span>
            <p>- Support Act Donation (5%)</p>
          </ReactTooltip>
          <img data-tip data-for='4' className={styles.planety} src='planeuta__x2B__Layer_7_xA0_Image (3).png'/>
          <ReactTooltip id='4' type='dark' effect='solid'>
            <span>60% minted</span>
            <p>- Artist Discovery Project Announced (For Season One)<br/>
            - Season Zero date announced</p>
          </ReactTooltip>
          <img data-tip data-for='5' className={styles.planety} src='planeuta__x2B__Layer_7_xA0_Image (4).png'/>
          <ReactTooltip id='5' type='dark' effect='solid'>
            <span>80% minted</span>
            <p>- MoonwalkerFM Merch Announcement/Drop date<br/>
              - MWFM 24/7 YT Channel launch</p>
          </ReactTooltip>
          <img data-tip data-for='6' className={styles.planety} src='planeuta__x2B__Layer_7_xA0_Image (5).png'/>
          <ReactTooltip id='6' type='dark' effect='solid'>
            <span>100% minted</span>
            <p>- Live Discord Q&A with team<br/>
- Moonwalker Ethereum Competition<br/>
- 20% Net revenue put aside for Season Zero Marketing<br/>
- Support Act Donation (5%)<br/>
- Rarity Sniper Listing</p>
          </ReactTooltip>
          </div>
        </Fade>
      :''}

      {tab==4 ?
        <Fade>
          <div className={styles.explore_container}>
            {tab!='4' ? <div hidden className={styles.mint_total}>
                          <h1>5000<span>AVAILABLE</span></h1>
                        </div> :
                        <img onClick={() => {setTab(0);setBlur(false)}} className={styles.close_button} src='/assets/Close Icon.svg'/>}
            <h1 className={styles.nav_title}>EXPLORE</h1>
            {tab!='4' ?<button>CONNECT WALLET</button> :
                        ''}

            <div className={!blur ? styles.explore_list : styles.explore_list_then}>
              {Array.apply(null, { length: 15 }).map((e, i) => (
                <div onClick={() => setBlur(true)} className={styles.explore_list_item}>
                  <img src='/demo2.jpg'/>
                  <div className={styles.explore_list_item_wrapper}>
                    <p>Moonwalker #4175</p>
                    <span>Rarity Score: 37</span>
                  </div>
                </div>
              ))}
            </div>
            {blur ? 

                <div className={styles.explore_list_blurred}>
                  <div className={styles.explore_list_blurred_wrapper}>
                  <p onClick={() => {setTab(4);setBlur(false)}} className={styles.backgo}><img src='/assets/backarrow.svg'/>BACK</p>
                    <div className={styles.explore_single}>
                        <Fade delay={200} className={styles.flex_fade}>
                          <img src='/demo2.jpg'/>
                        </Fade>
                        <Fade delay={450} className={styles.flex_fade}>
                          <div className={styles.explore_single_info}>
                              <div className={styles.explore_single_title}>
                                <p>Moonwalker #4175</p>
                                <span>RARITY SCORE: 37</span>
                              </div>
                              <br/><br/>
                              <div className={styles.explore_single_traits}>
                                <p>BACKGROUND<span>BIBLE PAGES</span></p>
                                <p>TATOOS<span>NONE</span></p>
                                <p>CLOTHING<span>WHITE TANK TOP</span></p>
                                <p>FACIAL HAIR<span>SIDE WHISKERS</span></p>
                                <p>EYEWEAR<span>NONE</span></p>
                                <p>HEADGEAR<span>CHANCE HAT</span></p>
                                <p>HAIR<span>BALD</span></p>
                                <p>ACCESSORIES<span>NONE</span></p>
                              </div>
                          </div>
                        </Fade>
                    </div>
                  </div>
                </div>:''}
          </div>
        </Fade>
      :''}

      {tab!='4' ? <div className={styles.bottom_bar}>
        {menu==false ? 
          <div>
                  <p onClick={() => setMenu(true)}>
                    <span>
                      <img src='/assets/menub.svg'/>
                    </span>
                    MENU
                  </p>
                </div> : 
          <div>
            <Fade>
              <ul className={styles.bottom_menu}>
                <li onClick={() => setTab(0)}><a><img className={styles.bottom_menu_img} src='/assets/Traits Icon.svg'/>HOME</a></li>
                <li onClick={() => setTab(1)}><a><img className={styles.bottom_menu_img} src='/assets/About Icon.svg'/>ABOUT</a></li>
                <li onClick={() => setTab(3)}><a><img className={styles.bottom_menu_img} src='/assets/Roadmap Icon.svg'/>ROADMAP</a></li>
                <li hidden onClick={() => setTab(4)}><a><img className={styles.bottom_menu_img} src='/assets/Search Icon.svg'/>EXPLORE</a></li>
              </ul>
              <ul className={styles.social_menu}>
              <li><a href='https://twitter.com/MoonwalkerFM'><img className={styles.bottom_menu_img_social} src='/assets/Twitter Icon.svg'/></a></li>
              <li><a href='https://discord.gg/RmAqW3cAhg'><img className={styles.bottom_menu_img_social} src='/assets/Discord Icon.svg'/></a></li>
              <li><a href='https://medium.com/@moonwalkerfm'><img className={styles.bottom_menu_img_social} src='/assets/IG Icon.svg'/></a></li>
              </ul>
            </Fade>
          </div>}
      </div>:''}
      { rightOpen ? 
        <div>
          <div className={styles.connect_modal} >
            <div className={styles.connect_hero}>
              <img onClick={() => setRightOpen(false)} src='/assets/Close Icon(2).svg'/>
              <span>{ wallet=='' ? 'SELECT WALLET':'MY WALLET'}</span>
              { wallet!='' ?<img className={styles.disc} onClick={disconnect} src='/assets/Disconnect Icon.svg'/>:''}
            </div>
            { wallet=='' ?
            <div className={styles.wallet_wrapper}>
              <div className={styles.wallet_item}>
                <img onClick={() => connectWallet('phantom')} src='https://upload.wikimedia.org/wikipedia/commons/3/36/MetaMask_Fox.svg'/>
                <p>METAMASK</p>
              </div>
            </div>
            :
            <div className={styles.wallet_wrapper}>
              <div className={styles.wallet_wrapper_empty}>
                <img src='/assets/Sad Face Icon.svg'/>
                <p>THERE ARE NO LIT JESUS NFT’S IN THIS WALLET</p>
              </div>
            </div>
          }
          </div>
        </div>
      :''}
    </div>
  )
}
