import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, {useRef,  useState, useEffect } from 'react';
import { Fade } from "react-awesome-reveal";
import Header from './components/header.js'
import { Navigation, Pagination, Scrollbar, A11y } from 'swiper';
import { Swiper, SwiperSlide } from 'swiper/react';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';
import "swiper/css/effect-cards"
import SwiperCore, {
    EffectCards
  } from 'swiper';
  SwiperCore.use([EffectCards]);
import { Connection, SystemProgram, clusterApiUrl } from '@solana/web3.js';



export default function Home() {
  const [menu, setMenu] = useState(false)
  const [blur, setBlur] = useState(false)
  const [tab, setTab] = useState(0)
  const [rightOpen, setRightOpen] = useState(false)
  const [wallet, setWallet] = useState('')
  const n = 15;



  const toggleSidebar = (event) => {
    setRightOpen(!rightOpen)
  }

  const connectWallet = async (wallet_url) => {
      const isPhantomInstalled = window.solana && window.solana.isPhantom
      const getProvider = () => {
        if ("solana" in window) {
          const provider = window.solana;
          if (provider.isPhantom) {
            console.log(provider)
            return provider;
          }
        }
        window.open("https://phantom.app/", "_blank");
      };
      window.solana.connect();
      window.solana.on("connect", () => {
        console.log("connected!");
        setWallet(window.solana.publicKey.toString())
      })
  }

  const disconnect = () => {
    window.solana.disconnect();
    setWallet('');
  }




  return (
    <div >
      <Head>
        <title>Lit Jesus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      {tab==0 ?
        <div className={styles.home_container}>
          <div className={styles.top_bar}>
            <div className={styles.mint_total}>
              <h1>777<span>AVAILABLE</span></h1>
            </div>
            <h1 className={styles.nav_title}>LIT JESUS</h1>
            {wallet=='' ? 
            <button onClick={toggleSidebar}>CONNECT WALLET</button>
            :<img className={styles.wallet_connected} src='/assets/Wallet Connected.svg'/>}
          </div>

          <Fade><div className={styles.mint_wrapper}></div></Fade>
        </div>
      :''}

      {tab==1 ?
        <Fade>
          <div className={styles.about_container}>
            <div className={styles.top_bar}>
              <div className={styles.mint_total}>
                <h1>777<span>AVAILABLE</span></h1>
              </div>
              <h1 className={styles.nav_title}>ABOUT</h1>
              {wallet=='' ? 
              <button onClick={toggleSidebar}>CONNECT WALLET</button>
              :<img className={styles.wallet_connected} src='/assets/Wallet Connected.svg'/>}
            </div>
            <div className={styles.about_wrapper}>
              <h1>THE WORLD’S FIRST GENERATIVE NFT PROJECT MADE FROM FINE ART PAINTINGS</h1>
              <p>After seeing many NFT projects making similiar algorithmically generated art, we founded Lit Jesus to bring something unique and differen’t to the space. We chose the Solana blockchain in hopes of doing our part to push the ecosystem forward in order to acheive mass adoption. Our art is a meme which represents the higher consciousness and divinity inherent in all people.</p>
              <div className={styles.horizontal_line}></div>
              <div className={styles.bottom_about}>
                <img src='/assets/abndgo.svg'/>
                <div className={styles.about_price}>
                  <h3>GENESIS 1 PRICE: 7◎</h3>
                  <p>Every NFT in GENESIS 1 comes with a 12x12” print. Whoever holds the most NFTs after 777 are sold will receive the final 30x40” canvas.</p>
                </div>
              </div>
            </div>
          </div>
        </Fade>
      :''}

      {tab==2 ?
        <Fade>
          <div className={styles.traits_container}>
            <div className={styles.top_bar}>
              <div className={styles.mint_total}>
                <h1>777<span>AVAILABLE</span></h1>
              </div>
              <h1 className={styles.nav_title}>TRAITS</h1>
              {wallet=='' ? 
              <button onClick={toggleSidebar}>CONNECT WALLET</button>
              :<img className={styles.wallet_connected} src='/assets/Wallet Connected.svg'/>}
            </div>
            <Swiper className={styles.swiper} effect={'cards'} grabCursor={true} >
              <SwiperSlide className={styles.swiper_slide}>Slide 1</SwiperSlide>
              <SwiperSlide className={styles.swiper_slide}>Slide 2</SwiperSlide>
              <SwiperSlide className={styles.swiper_slide}>Slide 3</SwiperSlide>
              <SwiperSlide className={styles.swiper_slide}>Slide 4</SwiperSlide>
              <SwiperSlide className={styles.swiper_slide}>Slide 5</SwiperSlide>
              <SwiperSlide className={styles.swiper_slide}>Slide 6</SwiperSlide>
              <SwiperSlide className={styles.swiper_slide}>Slide 7</SwiperSlide>
              <SwiperSlide className={styles.swiper_slide}>Slide 8</SwiperSlide>
              <SwiperSlide className={styles.swiper_slide}>Slide 9</SwiperSlide>
            </Swiper>
          </div>
        </Fade>
      :''}

      {tab==3 ?
        <Fade>
          <div className={styles.roadmap_container}>
            <div className={styles.top_bar}>
              <div className={styles.mint_total}>
                <h1>777<span>AVAILABLE</span></h1>
              </div>
              <h1 className={styles.nav_title}>ROADMAP</h1>
              {wallet=='' ? 
              <button onClick={toggleSidebar}>CONNECT WALLET</button>
              :<img className={styles.wallet_connected} src='/assets/Wallet Connected.svg'/>}
            </div>
            <h1 className={styles.roadmap_container_tab}>ROADMAP</h1>
          </div>
        </Fade>
      :''}

      {tab==4 ?
        <Fade>
          <div className={styles.explore_container}>
            {tab!='4' ? <div className={styles.mint_total}>
                          <h1>777<span>AVAILABLE</span></h1>
                        </div> :
                        <img onClick={() => {setTab(0);setBlur(false)}} className={styles.close_button} src='/assets/Close Icon.svg'/>}
            <h1 className={styles.nav_title}>EXPLORE</h1>
            {tab!='4' ?<button>CONNECT WALLET</button> :
                        ''}

            <div className={!blur ? styles.explore_list : styles.explore_list_then}>
              {Array.apply(null, { length: 15 }).map((e, i) => (
                <div onClick={() => setBlur(true)} className={styles.explore_list_item}>
                  <img src='/assets/test.svg'/>
                  <div className={styles.explore_list_item_wrapper}>
                    <p>GENESIS 1:24</p>
                    <span>Rarity Score: 37</span>
                  </div>
                </div>
              ))}
            </div>
            {blur ? 

                <div className={styles.explore_list_blurred}>
                  <div className={styles.explore_list_blurred_wrapper}>
                  <p onClick={() => {setTab(4);setBlur(false)}} className={styles.backgo}><img src='/assets/backarrow.svg'/>BACK</p>
                    <div className={styles.explore_single}>
                        <Fade delay={200} className={styles.flex_fade}>
                          <img src='/assets/test.svg'/>
                        </Fade>
                        <Fade delay={450} className={styles.flex_fade}>
                          <div className={styles.explore_single_info}>
                              <div className={styles.explore_single_title}>
                                <p>GENESIS 1:24</p>
                                <span>RARITY SCORE: 37</span>
                              </div>
                              <br/><br/>
                              <div className={styles.explore_single_traits}>
                                <p>BACKGROUND<span>BIBLE PAGES</span></p>
                                <p>TATOOS<span>NONE</span></p>
                                <p>CLOTHING<span>WHITE TANK TOP</span></p>
                                <p>FACIAL HAIR<span>SIDE WHISKERS</span></p>
                                <p>EYEWEAR<span>NONE</span></p>
                                <p>HEADGEAR<span>CHANCE HAT</span></p>
                                <p>HAIR<span>BALD</span></p>
                                <p>ACCESSORIES<span>NONE</span></p>
                              </div>
                          </div>
                        </Fade>
                    </div>
                  </div>
                </div>:''}
          </div>
        </Fade>
      :''}

      {tab!='4' ? <div className={styles.bottom_bar}>
        {menu==false ? 
          <div>
                  <p onClick={() => setMenu(true)}>
                    <span>
                      <img src='/assets/menub.svg'/>
                    </span>
                    MENU
                  </p>
                </div> : 
          <div>
            <Fade>
              <ul className={styles.bottom_menu}>
                <li onClick={() => setTab(1)}><a><img className={styles.bottom_menu_img} src='/assets/About Icon.svg'/>ABOUT</a></li>
                <li onClick={() => setTab(2)}><a><img className={styles.bottom_menu_img} src='/assets/Traits Icon.svg'/>TRAITS</a></li>
                <li onClick={() => setTab(3)}><a><img className={styles.bottom_menu_img} src='/assets/Roadmap Icon.svg'/>ROADMAP</a></li>
                <li onClick={() => setTab(4)}><a><img className={styles.bottom_menu_img} src='/assets/Search Icon.svg'/>EXPLORE</a></li>
              </ul>
              <ul className={styles.social_menu}>
              <li><a><img className={styles.bottom_menu_img} src='/assets/Twitter Icon.svg'/></a></li>
              <li><a><img className={styles.bottom_menu_img} src='/assets/Discord Icon.svg'/></a></li>
              <li><a><img className={styles.bottom_menu_img} src='/assets/IG Icon.svg'/></a></li>
              </ul>
            </Fade>
          </div>}
      </div>:''}
      { rightOpen ? 
        <div>
          <div className={styles.connect_modal} >
            <div className={styles.connect_hero}>
              <img onClick={() => setRightOpen(false)} src='/assets/Close Icon(2).svg'/>
              <span>{ wallet=='' ? 'SELECT WALLET':'MY WALLET'}</span>
              { wallet!='' ?<img className={styles.disc} onClick={disconnect} src='/assets/Disconnect Icon.svg'/>:''}
            </div>
            { wallet=='' ?
            <div className={styles.wallet_wrapper}>
              <div className={styles.wallet_item}>
                <img onClick={() => connectWallet('phantom')} src='/assets/phantom 1.svg'/>
                <p>PHANTOM</p>
              </div>
              <div hidden className={styles.wallet_item}>
                <img onClick={() => setWallet('solflare')} src='/assets/solflare 1.svg'/>
                <p>SOLFLARE</p>
              </div>
              <div hidden className={styles.wallet_item}>
                <img onClick={() => connectWallet('https://www.sollet.io')} src='/assets/sollet 1.svg'/>
                <p>SOLLET</p>
              </div>
              <div hidden className={styles.wallet_item}>
                <img onClick={() => setWallet('solong')} src='/assets/solong 1.svg'/>
                <p>SOLONG</p>
              </div>
            </div>
            :
            <div className={styles.wallet_wrapper}>
              <div className={styles.wallet_wrapper_empty}>
                <img src='/assets/Sad Face Icon.svg'/>
                <p>THERE ARE NO LIT JESUS NFT’S IN THIS WALLET</p>
              </div>
            </div>
          }
          </div>
        </div>
      :''}
    </div>
  )
}
